<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PEDREGALES DE MISNEBALAM</title>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: 'Montserrat', sans-serif;
      margin: 20px; /* Margen alrededor del cuerpo */
      padding: 0;
      background-image: url('C:/Users/Lenovo/Downloads/pedregales-imagen-pre.jpg'); /* Nueva imagen de fondo */
      background-size: cover;
      background-position: center; /* Centrar la imagen de fondo */
    }
    header, nav, section, footer {
      font-family: 'Montserrat', sans-serif;
      margin-bottom: 20px; /* Margen inferior para estos elementos */
    }
    header {
      background-color: #145A32; /* Azul */
      color: white;
      padding: 20px;
      text-align: center;
    }
    header img {
      width: 50%; /* Ancho de la imagen del título */
      height: auto; /* Altura automática para mantener la proporción */
    }
    nav {
      background-color: #E5C69E; /* Negro */
      padding: 10px;
      text-align: center;
    }
    nav a {
      text-decoration: none;
      color: #333; /* Negro */
      padding: 5px 20px;
      margin: 0 10px;
      border-radius: 5px;
    }
    nav a:hover {
      background-color: #E5C69E; /* Negro */
      color: white;
    }
    section {
      padding: 20px;
    }
    footer {
      background-color: #145A32; /* Azul */
      color: white;
      text-align: center;
      padding: 10px;
      position: fixed;
      bottom: 0;
      width: 100%;
    }
    .social-links {
      display: flex;
      justify-content: center;
    }
    .social-links a {
      margin: 0 10px;
      text-decoration: none;
      color: #145A32;
      font-weight: bold;
    }
  </style>
</head>
<body>

<header>
  <img src="C:\Users\Lenovo\Downloads\logotipopedregales123.png" alt="Logotipo de Pedregales de Misne Balam">
</header>
  
<section id="inicio" style="background-color: #145A32; border-radius: 10px; padding: 10px;">
  <h2 style="text-align: center; color: white;">Inicio</h2>
  <ul style="list-style-type: none; padding: 0; display: flex; justify-content: center;">
    <li style="margin: 0 5px;">
      <a href="https://drive.google.com/file/d/1EYymVSHuzu5GzOtdGz_LqMH5OYMVX6Yw/view?usp=drive_link" target="_blank" style="text-decoration: none; color: white; padding: 5px 10px; background-color: #145A32; border: 2px solid #145A32; border-radius: 5px;">Brochure General</a>
    </li>
    <li style="margin: 0 5px;">
      <a href="https://drive.google.com/drive/folders/1MjSlAn2MqgFdW1COF1Yo3hGN-YbnPJQd?usp=drive_link" target="_blank" style="text-decoration: none; color: white; padding: 5px 10px; background-color: #145A32; border: 2px solid #145A32; border-radius: 5px;">Flyers y Modelos</a>
    </li>
    <li style="margin: 0 5px;">
      <a href="https://drive.google.com/drive/folders/16kmi1Lzx2hOFaJ5o4l9RyN9JHhrhR6Od?usp=drive_link" target="_blank" style="text-decoration: none; color: white; padding: 5px 10px; background-color: #145A32; border: 2px solid #145A32; border-radius: 5px;">Ficha Técnica de Modelos</a>
    </li>
  </ul>
</section>

<section id="inicio">
  <h2>Enlaces Sociales</h2>
  <div class="social-links">
    <a href="https://api.whatsapp.com/send?phone=529993154455" target="_blank">WhatsApp</a>
    <a href="https://www.facebook.com/pedregalesmisnebalam?mibextid=ViGcVu" target="_blank">Facebook</a>
    <a href="https://www.instagram.com/misnenuevotemozon" target="_blank">Instagram</a>
  </div>
</section>
  

<section id="propiedades">
  <h2>Documentación</h2>
  <p>Aquí puedes encontrar revisar lo necesario para ser parte de Pedregales de Misenabalam.</p>
  <!-- Aquí puedes añadir la lista de propiedades  -->
  <ul>
    <li><a href="https://drive.google.com/uc?export=download&id=1SNiJDogQQ8M_MXjHkieGA9z_G0VWh4qj">Documentos a solicitar </a></li>
    <li><a href="https://drive.google.com/uc?export=download&id=1KgFKNTjicXiAM7K3HggVtvPGwRVwmw1o">Documentos a solicitar (extranjeros)</a></li>
  </ul>
</section>

<section id="ubicacion">
 

</section>
  <section id="ubicacion">
  <h2>Ubicación</h2>
  <a href="https://www.google.com.mx/maps/place/PEDREGALES+DE+MISNEBALAM/@21.1713125,-89.6061875,17z/data=!3m1!4b1!4m6!3m5!1s0x8f55d9c8007aebc7:0xc8e1c5be7d897a20!8m2!3d21.1713125!4d-89.6061875!16s%2Fg%2F11tfb_v3mc?entry=ttu" target="_blank"  >google maps</a>
</section>

<section id="formatos">
  <h2>Formatos a llenar y enviar</h2>
  <ul>
    <li><a href="https://drive.google.com/uc?export=download&id=1Nv_cVuMhLVScb5iEB596VUpg1fHFxPxk">Persona moral</a></li>
    <li><a href="https://drive.google.com/uc?export=download&id=1Vn0HXAvevwEnloQHOi-KU4nlyDGQltn5">persona moral extrangera</a></li>
  </ul>
</section>

<section id="contacto">
  <h2>Contacto</h2>
  <p>Ponte en contacto con nosotros para más información:</p>
  <ul>
   <p>Teléfono: 999-315-4455</p>
   <p>Dirección: Oficinas,Colonia México, Mérida, Yucatán, México</p>
  </ul>
</section>

<footer>
  <p>&copy; 2024 Pedregales De Misnebalam.</p>
</footer>

</body>
</html>
